table.insert(materials_from, {probability = 0.30, materials = { "graham_mundane"}})
table.insert(materials_from, {probability = 0.30, materials = { "graham_hellblood"}})
table.insert(materials_from, {probability = 0.30, materials = { "graham_slush"}})
table.insert(materials_from, {probability = 0.30, materials = { "graham_coffee"}})
table.insert(materials_from, {probability = 0.30, materials = { "graham_statium"}})
table.insert(materials_from, {probability = 0.30, materials = { "graham_bubbly"}})
table.insert(materials_from, {probability = 0.30, materials = { "graham_driedfungus"}})

table.insert(materials_to, {probability = 0.30, material = "graham_mundane"})
table.insert(materials_to, {probability = 0.30, material = "graham_hellblood"})
table.insert(materials_to, {probability = 0.30, material = "graham_slush"})
table.insert(materials_to, {probability = 0.30, material = "graham_precursor"})
table.insert(materials_to, {probability = 0.30, material = "graham_beans"})
table.insert(materials_to, {probability = 0.30, material = "graham_pureliquid"})
table.insert(materials_to, {probability = 0.10, material = "graham_stickyfungus"})
table.insert(materials_to, {probability = 0.10, material = "graham_meatgreedy"})
table.insert(materials_to, {probability = 0.10, material = "graham_meathealthy"})
table.insert(materials_to, {probability = 0.10, material = "graham_confuse"})