return [[<mBufferedPixelScenes>
<PixelScene pos_x="-2379" pos_y="6646" just_load_an_entity="mods/grahamsperks/files/entities/books/cookbook.xml"/>
<PixelScene pos_x="33461" pos_y="6646" just_load_an_entity="mods/grahamsperks/files/entities/books/cookbook.xml"/>
<PixelScene pos_x="-38219" pos_y="6646" just_load_an_entity="mods/grahamsperks/files/entities/books/cookbook.xml"/>
<PixelScene pos_x="9953" pos_y="-1167" just_load_an_entity="mods/grahamsperks/files/entities/books/polybook.xml"/>
<PixelScene pos_x="45793" pos_y="-1167" just_load_an_entity="mods/grahamsperks/files/entities/books/polybook.xml"/>
<PixelScene pos_x="-25887" pos_y="-1167" just_load_an_entity="mods/grahamsperks/files/entities/books/polybook.xml"/>
<PixelScene pos_x="-3811" pos_y="10113" just_load_an_entity="mods/grahamsperks/files/entities/books/lonelybook.xml"/>
<PixelScene pos_x="32029" pos_y="10113" just_load_an_entity="mods/grahamsperks/files/entities/books/lonelybook.xml"/>
<PixelScene pos_x="-39651" pos_y="10113" just_load_an_entity="mods/grahamsperks/files/entities/books/lonelybook.xml"/>
<PixelScene pos_x="-16268" pos_y="-7093" just_load_an_entity="mods/grahamsperks/files/entities/books/timebook.xml"/>
<PixelScene pos_x="19572" pos_y="-7093" just_load_an_entity="mods/grahamsperks/files/entities/books/timebook.xml"/>
<PixelScene pos_x="-52108" pos_y="-7093" just_load_an_entity="mods/grahamsperks/files/entities/books/timebook.xml"/>
<PixelScene pos_x="-1933" pos_y="-59" just_load_an_entity="mods/grahamsperks/files/entities/books/anvilbook.xml"/>
<PixelScene pos_x="4379" pos_y="895" just_load_an_entity="mods/grahamsperks/files/pickups/chest_tech.xml"/>
<PixelScene pos_x="40219" pos_y="895" just_load_an_entity="mods/grahamsperks/files/pickups/chest_tech.xml"/>
<PixelScene pos_x="-31461" pos_y="895" just_load_an_entity="mods/grahamsperks/files/pickups/chest_tech.xml"/>
<PixelScene pos_x="-12340" pos_y="420" just_load_an_entity="mods/grahamsperks/files/pickups/chest_tech.xml"/>
<PixelScene pos_x="23500" pos_y="420" just_load_an_entity="mods/grahamsperks/files/pickups/chest_tech.xml"/>
<PixelScene pos_x="-48180" pos_y="420" just_load_an_entity="mods/grahamsperks/files/pickups/chest_tech.xml"/>
<PixelScene pos_x="-3367" pos_y="3346" just_load_an_entity="mods/grahamsperks/files/pickups/chest_tech.xml"/>
<PixelScene pos_x="32473" pos_y="3346" just_load_an_entity="mods/grahamsperks/files/pickups/chest_tech.xml"/>
<PixelScene pos_x="-39207" pos_y="3346" just_load_an_entity="mods/grahamsperks/files/pickups/chest_tech.xml"/>
<PixelScene pos_x="2945" pos_y="12316" just_load_an_entity="mods/grahamsperks/files/pickups/chest_tech.xml"/>
<PixelScene pos_x="38785" pos_y="12316" just_load_an_entity="mods/grahamsperks/files/pickups/chest_tech.xml"/>
<PixelScene pos_x="-32895" pos_y="12316" just_load_an_entity="mods/grahamsperks/files/pickups/chest_tech.xml"/>
<PixelScene pos_x="12336" pos_y="-4642" just_load_an_entity="mods/grahamsperks/files/pickups/chest_tech.xml"/>
<PixelScene pos_x="48176" pos_y="-4642" just_load_an_entity="mods/grahamsperks/files/pickups/chest_tech.xml"/>
<PixelScene pos_x="-23504" pos_y="-4642" just_load_an_entity="mods/grahamsperks/files/pickups/chest_tech.xml"/>
<PixelScene pos_x="-1707" pos_y="-742" just_load_an_entity="mods/grahamsperks/files/pickups/chest_tech.xml"/>
<PixelScene pos_x="34133" pos_y="-742" just_load_an_entity="mods/grahamsperks/files/pickups/chest_tech.xml"/>
<PixelScene pos_x="-37547" pos_y="-742" just_load_an_entity="mods/grahamsperks/files/pickups/chest_tech.xml"/>
<PixelScene pos_x="9654" pos_y="9186" just_load_an_entity="mods/grahamsperks/files/pickups/chest_tech.xml"/>
<PixelScene pos_x="45494" pos_y="9186" just_load_an_entity="mods/grahamsperks/files/pickups/chest_tech.xml"/>
<PixelScene pos_x="-26186" pos_y="9186" just_load_an_entity="mods/grahamsperks/files/pickups/chest_tech.xml"/>
<PixelScene pos_x="3372" pos_y="1876" just_load_an_entity="mods/grahamsperks/files/pickups/chest_tech.xml"/>
<PixelScene pos_x="39212" pos_y="1876" just_load_an_entity="mods/grahamsperks/files/pickups/chest_tech.xml"/>
<PixelScene pos_x="-32468" pos_y="1876" just_load_an_entity="mods/grahamsperks/files/pickups/chest_tech.xml"/>
<PixelScene pos_x="-4324" pos_y="3968" just_load_an_entity="mods/grahamsperks/files/pickups/chest_tech.xml"/>
<PixelScene pos_x="31516" pos_y="3968" just_load_an_entity="mods/grahamsperks/files/pickups/chest_tech.xml"/>
<PixelScene pos_x="-40164" pos_y="3968" just_load_an_entity="mods/grahamsperks/files/pickups/chest_tech.xml"/>
<PixelScene pos_x="4413" pos_y="13087" just_load_an_entity="mods/grahamsperks/files/pickups/chest_tech.xml"/>
<PixelScene pos_x="40253" pos_y="13087" just_load_an_entity="mods/grahamsperks/files/pickups/chest_tech.xml"/>
<PixelScene pos_x="-31427" pos_y="13087" just_load_an_entity="mods/grahamsperks/files/pickups/chest_tech.xml"/>
<PixelScene pos_x="11480" pos_y="-4864" just_load_an_entity="mods/grahamsperks/files/wands/candyheart.xml"/>
<PixelScene pos_x="47320" pos_y="-4864" just_load_an_entity="mods/grahamsperks/files/wands/candyheart.xml"/>
<PixelScene pos_x="-24360" pos_y="-4864" just_load_an_entity="mods/grahamsperks/files/wands/candyheart.xml"/>
<PixelScene pos_x="10050" pos_y="-736" just_load_an_entity="mods/grahamsperks/files/wands/rotting.xml"/>
<PixelScene pos_x="45890" pos_y="-736" just_load_an_entity="mods/grahamsperks/files/wands/rotting.xml"/>
<PixelScene pos_x="-25790" pos_y="-736" just_load_an_entity="mods/grahamsperks/files/wands/rotting.xml"/>
<PixelScene pos_x="16090" pos_y="10000" just_load_an_entity="mods/grahamsperks/files/wands/coffee.xml"/>
<PixelScene pos_x="51930" pos_y="10000" just_load_an_entity="mods/grahamsperks/files/wands/coffee.xml"/>
<PixelScene pos_x="-19750" pos_y="10000" just_load_an_entity="mods/grahamsperks/files/wands/coffee.xml"/>
<PixelScene pos_x="2520" pos_y="7440" just_load_an_entity="mods/grahamsperks/files/wands/petworm.xml"/>
<PixelScene pos_x="38360" pos_y="7440" just_load_an_entity="mods/grahamsperks/files/wands/petworm.xml"/>
<PixelScene pos_x="-33320" pos_y="7440" just_load_an_entity="mods/grahamsperks/files/wands/petworm.xml"/>
<PixelScene pos_x="4135" pos_y="12964" just_load_an_entity="mods/grahamsperks/files/wands/gluestick.xml"/>
<PixelScene pos_x="39975" pos_y="12964" just_load_an_entity="mods/grahamsperks/files/wands/gluestick.xml"/>
<PixelScene pos_x="-31705" pos_y="12964" just_load_an_entity="mods/grahamsperks/files/wands/gluestick.xml"/>
<PixelScene pos_x="16161" pos_y="3333" just_load_an_entity="mods/grahamsperks/files/wands/experimental.xml"/>
<PixelScene pos_x="52001" pos_y="3333" just_load_an_entity="mods/grahamsperks/files/wands/experimental.xml"/>
<PixelScene pos_x="-19679" pos_y="3333" just_load_an_entity="mods/grahamsperks/files/wands/experimental.xml"/>
<PixelScene pos_x="1487" pos_y="6085" just_load_an_entity="mods/grahamsperks/files/entities/books/unlockbook.xml"/>
<PixelScene pos_x="37327" pos_y="6085" just_load_an_entity="mods/grahamsperks/files/entities/books/unlockbook.xml"/>
<PixelScene pos_x="-34353" pos_y="6085" just_load_an_entity="mods/grahamsperks/files/entities/books/unlockbook.xml"/>
<PixelScene pos_x="3435" pos_y="936" just_load_an_entity="mods/grahamsperks/files/pickups/vial.xml"/>
<PixelScene pos_x="39275" pos_y="936" just_load_an_entity="mods/grahamsperks/files/pickups/vial.xml"/>
<PixelScene pos_x="-32405" pos_y="936" just_load_an_entity="mods/grahamsperks/files/pickups/vial.xml"/>
<PixelScene pos_x="-2111" pos_y="2722" just_load_an_entity="mods/grahamsperks/files/pickups/balloon.xml"/>
<PixelScene pos_x="33729" pos_y="2722" just_load_an_entity="mods/grahamsperks/files/pickups/balloon.xml"/>
<PixelScene pos_x="-37951" pos_y="2722" just_load_an_entity="mods/grahamsperks/files/pickups/balloon.xml"/>
<PixelScene pos_x="-1908" pos_y="-56" just_load_an_entity="mods/grahamsperks/files/pixelscenes/text.xml"/>
<PixelScene pos_x="-1864" pos_y="-53" just_load_an_entity="data/entities/items/pickup/moon.xml"/>
<PixelScene pos_x="2372" pos_y="530" just_load_an_entity="mods/grahamsperks/files/pixelscenes/hands.xml"/>
<PixelScene pos_x="2382" pos_y="560" just_load_an_entity="mods/grahamsperks/files/entities/goldblood.xml"/>
<PixelScene pos_x="-2221" pos_y="2564" just_load_an_entity="mods/grahamsperks/files/pixelscenes/hellblood.xml"/>
<PixelScene pos_x="33619" pos_y="2564" just_load_an_entity="mods/grahamsperks/files/pixelscenes/hellblood.xml"/>
<PixelScene pos_x="-38061" pos_y="2564" just_load_an_entity="mods/grahamsperks/files/pixelscenes/hellblood.xml"/>
<PixelScene pos_x="-2490" pos_y="6480" just_load_an_entity="mods/grahamsperks/files/pixelscenes/transmutatium.xml"/>
<PixelScene pos_x="33350" pos_y="6480" just_load_an_entity="mods/grahamsperks/files/pixelscenes/transmutatium.xml"/>
<PixelScene pos_x="-38330" pos_y="6480" just_load_an_entity="mods/grahamsperks/files/pixelscenes/transmutatium.xml"/>
<PixelScene pos_x="3921" pos_y="3100" just_load_an_entity="mods/grahamsperks/files/entities/forge_item_check.xml"/>
<PixelScene pos_x="39761" pos_y="3100" just_load_an_entity="mods/grahamsperks/files/entities/forge_item_check.xml"/>
<PixelScene pos_x="-31919" pos_y="3100" just_load_an_entity="mods/grahamsperks/files/entities/forge_item_check.xml"/>
<PixelScene pos_x="3951" pos_y="3140" just_load_an_entity="mods/grahamsperks/files/pixelscenes/hand.xml"/>
<PixelScene pos_x="39791" pos_y="3140" just_load_an_entity="mods/grahamsperks/files/pixelscenes/hand.xml"/>
<PixelScene pos_x="-31889" pos_y="3140" just_load_an_entity="mods/grahamsperks/files/pixelscenes/hand.xml"/>
<PixelScene pos_x="-14638" pos_y="13031" just_load_an_entity="mods/grahamsperks/files/entities/forge_item_check.xml"/>
<PixelScene pos_x="21202" pos_y="13031" just_load_an_entity="mods/grahamsperks/files/entities/forge_item_check.xml"/>
<PixelScene pos_x="-50478" pos_y="13031" just_load_an_entity="mods/grahamsperks/files/entities/forge_item_check.xml"/>
<PixelScene pos_x="-14608" pos_y="13071" just_load_an_entity="mods/grahamsperks/files/pixelscenes/hand.xml"/>
<PixelScene pos_x="21232" pos_y="13071" just_load_an_entity="mods/grahamsperks/files/pixelscenes/hand.xml"/>
<PixelScene pos_x="-50448" pos_y="13071" just_load_an_entity="mods/grahamsperks/files/pixelscenes/hand.xml"/>
<PixelScene pos_x="2318" pos_y="1870" just_load_an_entity="mods/grahamsperks/files/entities/eyechecker.xml"/>
<PixelScene pos_x="38158" pos_y="1870" just_load_an_entity="mods/grahamsperks/files/entities/eyechecker.xml"/>
<PixelScene pos_x="-33522" pos_y="1870" just_load_an_entity="mods/grahamsperks/files/entities/eyechecker.xml"/>
<PixelScene pos_x="4573" pos_y="528" just_load_an_entity="mods/grahamsperks/files/pixelscenes/eye.xml"/>
<PixelScene pos_x="40413" pos_y="528" just_load_an_entity="mods/grahamsperks/files/pixelscenes/eye.xml"/>
<PixelScene pos_x="-31267" pos_y="528" just_load_an_entity="mods/grahamsperks/files/pixelscenes/eye.xml"/>
<PixelScene pos_x="2000" pos_y="1735" just_load_an_entity="mods/grahamsperks/files/pixelscenes/closedeye.xml"/>
<PixelScene pos_x="37840" pos_y="1735" just_load_an_entity="mods/grahamsperks/files/pixelscenes/closedeye.xml"/>
<PixelScene pos_x="-33840" pos_y="1735" just_load_an_entity="mods/grahamsperks/files/pixelscenes/closedeye.xml"/>
<PixelScene pos_x="-5302" pos_y="575" just_load_an_entity="mods/grahamsperks/files/pixelscenes/materials.xml"/>
<PixelScene pos_x="-6760" pos_y="7424" just_load_an_entity="mods/grahamsperks/files/pixelscenes/yinyang.xml"/>
<PixelScene pos_x="29080" pos_y="7424" just_load_an_entity="mods/grahamsperks/files/pixelscenes/yinyang.xml"/>
<PixelScene pos_x="-42600" pos_y="7424" just_load_an_entity="mods/grahamsperks/files/pixelscenes/yinyang.xml"/>
<PixelScene pos_x="-6693" pos_y="7515" just_load_an_entity="mods/grahamsperks/files/entities/halo_checker.xml"/>
<PixelScene pos_x="29147" pos_y="7515" just_load_an_entity="mods/grahamsperks/files/entities/halo_checker.xml"/>
<PixelScene pos_x="-42533" pos_y="7515" just_load_an_entity="mods/grahamsperks/files/entities/halo_checker.xml"/>
<PixelScene pos_x="11537" pos_y="9956" just_load_an_entity="mods/grahamsperks/files/pixelscenes/water.xml"/>
<PixelScene pos_x="11537" pos_y="9986" just_load_an_entity="mods/grahamsperks/files/pickups/chest_immunity.xml"/>
<PixelScene pos_x="-317" pos_y="-1673" just_load_an_entity="mods/grahamsperks/files/pixelscenes/island.xml"/>
<PixelScene pos_x="-278" pos_y="-1580" just_load_an_entity="mods/grahamsperks/files/entities/fireplace_worse.xml"/>
<PixelScene pos_x="-46" pos_y="-1550" just_load_an_entity="mods/grahamsperks/files/entities/books/cozybook.xml"/>
<PixelScene pos_x="4046" pos_y="12977" just_load_an_entity="mods/grahamsperks/files/pixelscenes/secret.xml"/>
<PixelScene pos_x="39886" pos_y="12977" just_load_an_entity="mods/grahamsperks/files/pixelscenes/secret.xml"/>
<PixelScene pos_x="-31794" pos_y="12977" just_load_an_entity="mods/grahamsperks/files/pixelscenes/secret.xml"/>
<PixelScene pos_x="4532" pos_y="13081" just_load_an_entity="mods/grahamsperks/files/entities/perk_spawners/map_spawner.xml"/>
<PixelScene pos_x="785" pos_y="-1231" just_load_an_entity="mods/grahamsperks/files/entities/perk_spawners/map2_spawner.xml"/>
<PixelScene pos_x="3546" pos_y="13100" just_load_an_entity="mods/grahamsperks/files/entities/perk_spawners/slots_spawner.xml"/>
<PixelScene pos_x="14241" pos_y="16284" just_load_an_entity="mods/grahamsperks/files/entities/forge_item_check.xml"/>
<PixelScene pos_x="50081" pos_y="16284" just_load_an_entity="mods/grahamsperks/files/entities/forge_item_check.xml"/>
<PixelScene pos_x="-21599" pos_y="16284" just_load_an_entity="mods/grahamsperks/files/entities/forge_item_check.xml"/>
<PixelScene pos_x="4692" pos_y="652" just_load_an_entity="mods/grahamsperks/files/entities/tear_secret.xml"/>
<PixelScene pos_x="40532" pos_y="652" just_load_an_entity="mods/grahamsperks/files/entities/tear_secret.xml"/>
<PixelScene pos_x="-31148" pos_y="652" just_load_an_entity="mods/grahamsperks/files/entities/tear_secret.xml"/>
<PixelScene pos_x="14271" pos_y="16324" just_load_an_entity="mods/grahamsperks/files/pixelscenes/hand.xml"/>
<PixelScene pos_x="50111" pos_y="16324" just_load_an_entity="mods/grahamsperks/files/pixelscenes/hand.xml"/>
<PixelScene pos_x="-21569" pos_y="16324" just_load_an_entity="mods/grahamsperks/files/pixelscenes/hand.xml"/>
<PixelScene pos_x="-16295" pos_y="-7140" just_load_an_entity="mods/grahamsperks/files/pixelscenes/home.xml"/>
<PixelScene pos_x="-16238" pos_y="-6987" just_load_an_entity="data/entities/props/furniture_bed.xml"/>
<PixelScene pos_x="-16116" pos_y="-7004" just_load_an_entity="data/entities/props/furniture_wood_table.xml"/>
<PixelScene pos_x="-16016" pos_y="-7068" just_load_an_entity="mods/grahamsperks/files/pickups/chest_lost.xml"/>
<PixelScene pos_x="-16117" pos_y="-7015" just_load_an_entity="mods/grahamsperks/files/pickups/chest_mini.xml"/>
<PixelScene pos_x="-16038" pos_y="-7010" just_load_an_entity="mods/grahamsperks/files/entities/fireplace_worse.xml"/>
<PixelScene pos_x="7412" pos_y="6175" just_load_an_entity="mods/grahamsperks/files/pixelscenes/heart.xml"/>
<PixelScene pos_x="43252" pos_y="6175" just_load_an_entity="mods/grahamsperks/files/pixelscenes/heart.xml"/>
<PixelScene pos_x="-28428" pos_y="6175" just_load_an_entity="mods/grahamsperks/files/pixelscenes/heart.xml"/>
<PixelScene pos_x="12055" pos_y="2700" just_load_an_entity="mods/grahamsperks/files/pixelscenes/wealth.xml"/>
<PixelScene pos_x="12055" pos_y="2730" just_load_an_entity="mods/grahamsperks/files/entities/midas_curse.xml"/>
<PixelScene pos_x="1800" pos_y="6600" just_load_an_entity="mods/grahamsperks/files/pixelscenes/egg.xml"/>
<PixelScene pos_x="37640" pos_y="6600" just_load_an_entity="mods/grahamsperks/files/pixelscenes/egg.xml"/>
<PixelScene pos_x="-34040" pos_y="6600" just_load_an_entity="mods/grahamsperks/files/pixelscenes/egg.xml"/>
<PixelScene pos_x="1800" pos_y="6600" just_load_an_entity="mods/grahamsperks/files/pickups/egg.xml"/>
<PixelScene pos_x="37640" pos_y="6600" just_load_an_entity="mods/grahamsperks/files/pickups/egg.xml"/>
<PixelScene pos_x="-34040" pos_y="6600" just_load_an_entity="mods/grahamsperks/files/pickups/egg.xml"/>
<PixelScene pos_x="1800" pos_y="6600" just_load_an_entity="mods/grahamsperks/files/entities/books/eggbook.xml"/>
<PixelScene pos_x="37640" pos_y="6600" just_load_an_entity="mods/grahamsperks/files/entities/books/eggbook.xml"/>
<PixelScene pos_x="-34040" pos_y="6600" just_load_an_entity="mods/grahamsperks/files/entities/books/eggbook.xml"/>
<PixelScene pos_x="-11695" pos_y="600" just_load_an_entity="mods/grahamsperks/files/pixelscenes/stargazer.xml"/>
<PixelScene pos_x="24145" pos_y="600" just_load_an_entity="mods/grahamsperks/files/pixelscenes/stargazer.xml"/>
<PixelScene pos_x="-47535" pos_y="600" just_load_an_entity="mods/grahamsperks/files/pixelscenes/stargazer.xml"/>
<PixelScene pos_x="0" pos_y="60000" just_load_an_entity="mods/grahamsperks/files/pixelscenes/cat.xml"/>
<PixelScene pos_x="35840" pos_y="60000" just_load_an_entity="mods/grahamsperks/files/pixelscenes/cat.xml"/>
<PixelScene pos_x="-35840" pos_y="60000" just_load_an_entity="mods/grahamsperks/files/pixelscenes/cat.xml"/>
<PixelScene pos_x="0" pos_y="-60000" just_load_an_entity="mods/grahamsperks/files/pixelscenes/cat2.xml"/>
<PixelScene pos_x="35840" pos_y="-60000" just_load_an_entity="mods/grahamsperks/files/pixelscenes/cat2.xml"/>
<PixelScene pos_x="-35840" pos_y="-60000" just_load_an_entity="mods/grahamsperks/files/pixelscenes/cat2.xml"/>
<PixelScene pos_x="3331" pos_y="1616" just_load_an_entity="mods/grahamsperks/files/entities/progress/progress.xml"/>
<PixelScene pos_x="39171" pos_y="1616" just_load_an_entity="mods/grahamsperks/files/entities/progress/progress.xml"/>
<PixelScene pos_x="-32509" pos_y="1616" just_load_an_entity="mods/grahamsperks/files/entities/progress/progress.xml"/>
<PixelScene pos_x="15090" pos_y="-3333" just_load_an_entity="mods/grahamsperks/files/entities/perk_spawners/ll_spawner.xml"/>
]]