if ALL_ENTITIES == nil then return end
table.insert(ALL_ENTITIES, {
    name="Graham's Things entities",
    desc="",
    icon="mods/grahamsperks/files/conjurer/entities/healthy_heart.png",
    icon_off="mods/grahamsperks/files/conjurer/entities_off.png",
    entities={
        {
            name="$graham_healthyheart_name",
            image="mods/grahamsperks/files/conjurer/entities/healthy_heart.png",
            path="mods/grahamsperks/files/pickups/heart_healthy.xml",
        },
        {
            name="$graham_bloodmoon_name",
            image="mods/grahamsperks/files/pickups/bloodmoon_ui.png",
            path="mods/grahamsperks/files/pickups/bloodmoon_ui.xml",
        },
        {
            name="$graham_cybereye_name",
            image="mods/grahamsperks/files/pickups/cybereye_ui.png",
            path="mods/grahamsperks/files/pickups/cybereye.xml",
        },
        {
            name="$graham_magmacore_name",
            image="mods/grahamsperks/files/pickups/magmastone.png",
            path="mods/grahamsperks/files/pickups/magmastone.xml",
        },
        {
            name="$graham_safe_name",
            image="mods/grahamsperks/files/pickups/safe_ui.png",
            path="mods/grahamsperks/files/pickups/safe.xml",
        },
        {
            name="$item_balloon_name",
            image="mods/grahamsperks/files/pickups/balloon_inv.png",
            path="mods/grahamsperks/files/pickups/balloon.xml",
        },
        {
            name="$graham_unstainer_name",
            image="mods/grahamsperks/files/pickups/soapstone_ui.png",
            path="mods/grahamsperks/files/pickups/soapstone.xml",
        },
        {
            name="$graham_crystal_ball_name",
            image="mods/grahamsperks/files/pickups/crystal_ball_ui.png",
            path="mods/grahamsperks/files/pickups/crystal_ball.xml",
        },
        {
            name="$item_burger",
            image="mods/grahamsperks/files/pickups/burg.png",
            path="mods/grahamsperks/files/pickups/burg.xml",
        },
        {
            name="$graham_runestone_phase",
            image="mods/grahamsperks/files/conjurer/entities/runestone_phase.png",
            path="data/entities/items/pickup/runestones/runestone_graham_phase.xml",
        },
        {
            name="$graham_lovelydie_name",
            image="mods/grahamsperks/files/pickups/lovely_die.png",
            path="mods/grahamsperks/files/pickups/lovely_die.xml",
        },
        {
            name="$graham_chest_mini",
            image="mods/grahamsperks/files/conjurer/entities/chest_mini.png",
            path="mods/grahamsperks/files/pickups/chest_mini.xml",
        },
        {
            name="$graham_chest_bloody",
            image="mods/grahamsperks/files/conjurer/entities/chest_bloody.png",
            path="mods/grahamsperks/files/pickups/chest_bloody.xml",
        },
        {
            name="$graham_chest_lost",
            image="mods/grahamsperks/files/conjurer/entities/chest_lost.png",
            path="mods/grahamsperks/files/pickups/chest_lost.xml",
        },
        {
            name="$graham_chest_immunity",
            image="mods/grahamsperks/files/conjurer/entities/chest_immunity.png",
            path="mods/grahamsperks/files/pickups/chest_immunity.xml",
        },
        {
            name="$graham_chest_tech",
            image="mods/grahamsperks/files/conjurer/entities/chest_tech.png",
            path="mods/grahamsperks/files/pickups/chest_tech.xml",
        },
        {
            name="$graham_wand_glue",
            image="mods/grahamsperks/files/conjurer/entities/gluestick.png",
            path="mods/grahamsperks/files/wands/gluestick.xml",
        },
        {
            name="$graham_wand_coffee",
            image="mods/grahamsperks/files/conjurer/entities/coffee.png",
            path="mods/grahamsperks/files/wands/coffee.xml",
        },
        {
            name="$graham_wand_worm",
            image="mods/grahamsperks/files/conjurer/entities/petworm.png",
            path="mods/grahamsperks/files/wands/petworm.xml",
        },
        {
            name="$graham_wand_rot",
            image="mods/grahamsperks/files/conjurer/entities/rotting.png",
            path="mods/grahamsperks/files/wands/rotting.xml",
        },
        {
            name="$graham_wand_heart",
            image="mods/grahamsperks/files/conjurer/entities/candyheart.png",
            path="mods/grahamsperks/files/wands/candyheart.xml",
        },
        {
            name="$graham_wand_experimental",
            image="mods/grahamsperks/files/conjurer/entities/experimental.png",
            path="mods/grahamsperks/files/wands/experimental.xml",
        },
        {
            name="$animal_graham_fuzz",
            image="data/ui_gfx/animal_icons/graham_fuzz.png",
            path="data/entities/animals/graham_fuzz.xml",
        },
        {
            name="$animal_mini_mimic",
            image="mods/grahamsperks/files/conjurer/entities/mini_mimic.png",
            path="data/entities/animals/mini_mimic.xml",
        },
        {
            name="$animal_bloody_mimic",
            image="mods/grahamsperks/files/conjurer/entities/bloody_mimic.png",
            path="data/entities/animals/bloody_mimic.xml",
        },
        {
            name="$animal_graham_miner_gasser",
            image="data/ui_gfx/animal_icons/graham_miner_gasser.png",
            path="data/entities/animals/graham_miner_gasser.xml",
        },
        {
            name="$animal_graham_gasser_hell",
            image="data/ui_gfx/animal_icons/graham_gasser_hell.png",
            path="data/entities/animals/graham_gasser_hell.xml",
        },
        {
            name="$animal_graham_wizard_familiar",
            image="data/ui_gfx/animal_icons/graham_wizard_familiar.png",
            path="data/entities/animals/graham_wizard_familiar.xml",
        },
    },
  })